### PR TITLE
Panel documentation

### PR DESCRIPTION
**Pull request by manuel12**
Solves #192

I also added all the .md files on docs folder, in order to not have such a messy root folder.

I added a RESUABLE_COMPONENTS.md files explaining where to find and what to use for the different reusable componets.

I also added image examples of each and saved the images in the folder with the same name.

### CODE REVIEW

**Comment by manuel12** [comment]
Looks like there are some merge conflicts, I will investigate how to merge.

**Comment by gbowne1** [comment]
I'm not sure why that would conflict.

**Review by gbowne1 — APPROVED** [review]
Approving for merge.  This looks good.

**Review by pawel975 — APPROVED** [review]
Great! Approve changes!

**Comment by manuel12** [comment]
> I'm not sure why that would conflict.

Me neither :/ was super easy to resolve with command line thought. All good now.

**Pull request merged**
