### PR TITLE
Solved #152 issue

### PR DESCRIPTION
**Pull request by munnokd**
Hey, @gbowne1 and @pawel975  I solved the #152 issue please merge this pull request.

### CODE REVIEW

**Review by gbowne1 — CHANGES_REQUESTED** [review]
This is not the correct change.  This change only affects the SideNav.

The correct change needs to affect only the X icon in the components and not the SideNav.  The SideNav Component X icon appears correctly and should not be changed.

With the newly re-organized files in /src/pages/ each component has a .css file with the CSS variable .Close-button needs its color changed inside its brackets.  

I believe thats the best way to change this correctly other than we use a file named variables.css

**Comment by munnokd** [comment]
Ya but the Sidebar component is into `src/layout/SideNav` so I changed only the X bar icon which is present in this SideNav.css file.

**Comment by gbowne1** [comment]
@munnokd I don't know.  I think there was some misunderstanding. That's not the correct change.

**Comment by pawel975** [comment]
@munnokd could you provide photo of solution? Background property seams to not solve the problem but rather color do.

**Comment by gbowne1** [comment]
@pawel975 I think this becuse in the components.. the CSS file has .Close-button with a "blue" background color..

He's trying to apply the change to the SideNav "X" instead of the ones in header of all the components/panels.

**Comment by pawel975** [comment]
@gbowne1 could provide photo? I can't clone repo right now. Background color wouldn't affect icon color, color property would do that I guess.

**Comment by gbowne1** [comment]
Sure @pawel975 an example of this is:

Screenshot 2023-04-07 at 15-03-39 React Social Media App

The X in here should be a light color, instead of a dark X.

**Comment by pawel975** [comment]
> Sure @pawel975 an example of this is:
> 
> Screenshot 2023-04-07 at 15-03-39 React Social Media App
> 
> The X in here should be a light color, instead of a dark X.  The screenshot doesn't do it any justice.  The header on my screen is very dark.. and this screen shot is lighter than what actually appears at least in my view.

Yeah I know how it looks like, I meant to see @munnokd solution to compare

**Comment by gbowne1** [comment]
He's trying to change the SideNav X, which is completely fine and is visible the way it is (in both modes) and should not be changed at all.

**Comment by manuel12** [comment]
@gbowne1 @pawel975 Is this reviewable already or are we waiting for a change?

**Comment by pawel975** [comment]
> @gbowne1 @pawel975 Is this reviewable already or are we waiting for a change?

We're waiting for change. Cross button should be changed across pages

**Comment by gbowne1** [comment]
I doubt we will see a change in this.  I would suggest closing this PR, as we also have more changes that will fix this.

**Pull request closed without merging**
