### PR TITLE
Eslint config fix

### PR DESCRIPTION
**Pull request by pawel975**
I deleted some settings that causes errors and redundant warnings according  to #210

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
Apprpving for merge

**Comment by gbowne1** [comment]
I don't know that I would remove every single bit of the ESLint and Prettier configuration.  create-react-app needs its own ESLint config. it's built in to CRA.

From what I have been reading, ESLint is not recommended to be installed globally.

you can see where it is installed if you run `npm ls eslint`

https://create-react-app.dev/docs/setting-up-your-editor/

We need to at least have the eslint extends for "react-app" and ""react-app/jest""

If we just want to enforce style we should use Prettier instead of ESLint style rules.

https://stackoverflow.com/questions/59633005/how-is-eslint-integrated-into-create-react-app

**Review by manuel12 — APPROVED** [review]
Approve changes!

**Comment by manuel12** [comment]
@pawel975 I see there are conflicts now after I merge backend branch into main. Now the files affected by your commit (.eslintrc, package.json and package-lock.json) are all located inside the client/ folder.

Please tell me if you need any info or help on solving the conflicts.

**Comment by pawel975** [comment]
I will handle thoss conflicts @gbowne1 @manuel12

**Comment by pawel975** [comment]
> I don't know that I would remove every single bit of the ESLint and Prettier configuration.  create-react-app needs its own ESLint config. it's built in to CRA.
> 
> From what I have been reading, ESLint is not recommended to be installed globally.
> 
> you can see where it is installed if you run `npm ls eslint`
> 
> https://create-react-app.dev/docs/setting-up-your-editor/
> 
> We need to at least have the eslint extends for "react-app" and ""react-app/jest""
> 
> If we just want to enforce style we should use Prettier instead of ESLint style rules.
> 
> https://stackoverflow.com/questions/59633005/how-is-eslint-integrated-into-create-react-app

Ok, I will dive into this and apply.

**Comment by gbowne1** [comment]
The structure has changed.  So some aspects of this issue may have changed.  I made a few Issues today surrounding some of the things I have noticed.

**Comment by pawel975** [comment]
I've resloved conflicts and udpate eslint file to extend rules according to CRA docs.

**Review by gbowne1 — APPROVED** [review]
Re- Approving merge conflict changes for merging.

**Review by manuel12 — APPROVED** [review]
Changes approved!

**Pull request merged**
