### PR TITLE
issue #60 - Added MUI icons to SideNav component

### PR DESCRIPTION
**Pull request by Dylan-Clarry**
220217898-8a031ff7-9893-4246-ade7-bf6f676c9ef6

- Changes in files:
    - SideNav.jsx
    - SideNav.css
- Added Material UI Icons to SideNav component
- Removed unused functions and state hook

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
This looks great.  Approving  for merge && merging. Thanks for the opportunity to review your PR and merge @Dylan-Clarry!

**Comment by gbowne1** [comment]
Feel free to work on anything else.  There is a lot of stuff that needs moved to MUI components.

**Comment by gbowne1** [comment]
Great! welcome you to the project!  There are 20+ Issues.. and there are certainly more but most of them CSS and TODO's.. have a look through them. I will assign you to whatever you think you can do.  Plenty of them are bordering stale (several weeks old).

**Comment by gbowne1** [comment]
I do wanna move the top bar to use MUI AppBar:

https://mui.com/material-ui/react-app-bar/

**Comment by Dylan-Clarry** [comment]
I can tackle the React drawer one tomorrow since I just worked on the SideNav. If you make an issue feel free to assign it to me :)

**Comment by gbowne1** [comment]
Alrighty. Shouldn't be too hard considering it's mostly built already.  :+1:

**Comment by gbowne1** [comment]
Issue created

**Pull request merged**
