### PR TITLE
Worked On the issue : Add method to accept cookies #54

### PR DESCRIPTION
**Pull request by goutham03062001**
Hello, I have worked on the issue on creating a modal box for accepting cookies from user.

Here is the screenshot of the output. And when ever a user refresh a page then we wait for 3seconds and then this modal box will popup. In the future we can handle this modal if he accepted cookies or not.

Screenshot (319)

### CODE REVIEW

**Review by pawel975 — APPROVED** [review]
Nice, approve changes for merge!

**Review by gbowne1 — APPROVED** [review]
Checked out this change and tested locally.  This change looks good.  My only concern is that this is now a part of login component, not a higher level compnent which is its own component that we can then load at any time in the process.  Otherwise this looks good.  What do you think @pawel975 ?

**Comment by goutham03062001** [comment]
Yeah, I thought about it exactly @gbowne1. But in most of the websites the cookies only shows in the home/Index page. It would be better if we have a separate landing page for path="/" Instead of registration. So we can play with this model as we want. If a user accept the cookies then we can allow him to sign up further.

**Comment by gbowne1** [comment]
Ah ok cool.  I am new to that side of the problem.  I just know it will be needed outside of the US.

**Comment by pawel975** [comment]
Merging changes to main.

**Pull request merged**
