### PR TITLE
Updated the outdated packages in client and server #278

### PR DESCRIPTION
**Pull request by balajik**
#278 Updated the client and server outdated packages.

**Client:**
```Package                      Current   Wanted   Latest  Location                                  Depended by
@babel/core                   7.21.8   7.23.0   7.23.0  node_modules/@babel/core                  client
@babel/eslint-parser          7.21.8  7.22.15  7.22.15  node_modules/@babel/eslint-parser         client
@emotion/react               11.11.0  11.11.1  11.11.1  node_modules/@emotion/react               client
@hookform/resolvers           2.9.11   2.9.11    3.3.1  node_modules/@hookform/resolvers          client
@mui/icons-material          5.11.16  5.14.12  5.14.12  node_modules/@mui/icons-material          client
@mui/material                 5.13.2  5.14.12  5.14.12  node_modules/@mui/material                client
@mui/system                   5.13.2  5.14.12  5.14.12  node_modules/@mui/system                  client
@mui/x-date-pickers            6.5.0   6.16.0   6.16.0  node_modules/@mui/x-date-pickers          client
@testing-library/dom           9.3.0    9.3.3    9.3.3  node_modules/@testing-library/dom         client
@testing-library/jest-dom     5.16.5   5.17.0    6.1.3  node_modules/@testing-library/jest-dom    client
@testing-library/react        13.4.0   13.4.0   14.0.0  node_modules/@testing-library/react       client
@testing-library/user-event   14.4.3   14.5.1   14.5.1  node_modules/@testing-library/user-event  client
babel-loader                   9.1.2    9.1.3    9.1.3  node_modules/babel-loader                 client
dayjs                         1.11.7  1.11.10  1.11.10  node_modules/dayjs                        client
dotenv                        16.0.3   16.3.1   16.3.1  node_modules/dotenv                       client
eslint                        8.41.0   8.50.0   8.50.0  node_modules/eslint                       client
eslint-config-prettier         8.8.0   8.10.0    9.0.0  node_modules/eslint-config-prettier       client
eslint-plugin-prettier         4.2.1    4.2.1    5.0.0  node_modules/eslint-plugin-prettier       client
eslint-plugin-react           7.32.2   7.33.2   7.33.2  node_modules/eslint-plugin-react          client
jest-watch-typeahead           0.6.5    0.6.5    2.2.2  node_modules/jest-watch-typeahead         client
prettier                       2.8.8    2.8.8    3.0.3  node_modules/prettier                     client
react-hook-form               7.43.9   7.47.0   7.47.0  node_modules/react-hook-form              client
react-router                  6.11.2   6.16.0   6.16.0  node_modules/react-router                 client
react-router-dom              6.11.2   6.16.0   6.16.0  node_modules/react-router-dom             client
web-vitals                     3.3.1    3.5.0    3.5.0  node_modules/web-vitals                   client
webpack                       5.83.1   5.88.2   5.88.2  node_modules/webpack                      client
yup                            1.1.1    1.3.2    1.3.2  node_modules/yup                          client
```

**Server:**
```Package      Current  Wanted  Latest  Location                  Depended by
debug          2.6.9   2.6.9   4.3.4  node_modules/debug        server
http-errors    1.6.3   1.6.3   2.0.0  node_modules/http-errors  server
morgan         1.9.1   1.9.1  1.10.0  node_modules/morgan       server
```

### CODE REVIEW

**Comment by gbowne1** [comment]
Ok, can do that.

**Comment by gbowne1** [comment]
I thought about adding express-rate-limit package to keep the API from getting hit with an overload of requests.

**Comment by gbowne1** [comment]
No we never set up Winston and Morgan, Helmet,  Lodash, etc..

I am sure we could find better packages as we work through issues and features.

Manuel did a lot of the backend, testing, server etc.

**Comment by gbowne1** [comment]
Might even be a good idea to add nodemon.  I know we have some of these packages installed.  I also considered adding Tailwind on the client side to enhance MUI.  We did that with CodeBooker it works fine together.  Oh and we are using Jest, RTL, and Cypress.  We don't have CI/CD yet either.

**Review by manuel12 — APPROVED** [review]
This works well for me when cloning and testing on balajik's repo. Well done! :)

**Pull request merged**
