### PR TITLE
Help center initial work

### LINKED ISSUE #124: [TODO] Add a Help feature modal widget
**Is your feature request related to a problem? Please describe.**

App is missing a Help center accessible from the user icon menu.

**Describe the solution you'd like**
Routes to /help

**Describe alternatives you've considered**

This could be a whole page, just a widget or a modal, etc. etc.  Facebook's is a whole page

**Additional context**

### PR DESCRIPTION
**Pull request by pawel975**
## Description

I did initial work for help center. Every help subcategory is achievable at different route.
Data is mocked in JSON file, in future it would be changed on database fetched data. Content could be in form of html in string format and the parsed in help center component (It would allow to create more sophisticated help documentation then simple text 😄 )

image

Fixes #124

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manually 

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
Checked out this change and tested locally.   This change appears to function correctly as the first stages of implementing the help center.

Approving for merge.

**Review by manuel12 — APPROVED** [review]
Great job, approving changes.

**Comment by pawel975** [comment]
PR has merge conflicts, I will resolve them and merge to main.

**Comment by gbowne1** [comment]
Yeah I figured one or both would cause a conflict.  Thanks @pawel975 @manuel12

**Review by gbowne1 — COMMENTED** [review]
Approving these changes for merge.

**Pull request merged**
