### PR TITLE
Feat: Create Profile Modal

### PR DESCRIPTION
**Pull request by promise-dash**
Fixed issue #199 
Feature Added: Created a profile modal in Profile.jsx and the respective styling has been implemented in Profile.css.

### CODE REVIEW

**Comment by gbowne1** [comment]
Do you have a screenshot of the working feature? @promise-dash 

There are some conflicts too.

Thanks

**Comment by promise-dash** [comment]
Ya sure.
sc1
sc2

**Review by gbowne1 — APPROVED** [review]
This looks good.  Fix the conflicting files.  Can you provide a screenshot of the working feature?

We have custom reusable components like CloseButton, Panel etc.  

Approving for merge

**Comment by promise-dash** [comment]
Working

w

**Comment by promise-dash** [comment]
I dont know why the "Resolve conflicts" button is disabled in this page.

**Comment by pawel975** [comment]
It looks good to me, could also adjust styles to whole app design? Approve for merge anyway!

**Review by pawel975 — APPROVED** [review]

**Comment by gbowne1** [comment]
Right now I will go for new contributors submit working features over styling @pawel975 

We can iterate over styling easily once its visible and working

@promise-dash this still has conflicts

**Comment by promise-dash** [comment]
@manuel12, yes the conflicts can be resolved as I have only added the "form" logic in creating the modal.
I tried to resolve it, but I m not getting which part of the code is creating this conflict.

**Comment by manuel12** [comment]
@promise-dash It says issues are in Profile.jsx and Profile.css. In any case cloned external repo and checked the profile Modal and it looks good. Approving for merge!

**Review by manuel12 — APPROVED** [review]

**Comment by gbowne1** [comment]
Probably just needs to accept incoming changes using the CLI  @promise-dash @manuel12

**Comment by promise-dash** [comment]
But in my case, no "command line instruction" button/option is available.

cl

**Comment by gbowne1** [comment]
Hmm.   @promise-dash Are you using a clone or a fork? They are different.

Ome of them you wont have command line access.  I forget which.

**Comment by manuel12** [comment]
@promise-dash I have an idea that could work:
Since you only changed 2 files (Profile.jsx and Profile.css) I recommend  you to have those 2 files saved locally on your computer,  and close this PR. 

Then clone or fork our repo again from scratch (so you get our latest changes) and then update  Profile.jsx and Profile.css (which will be located now on folder client/src/pages/Profile) commit and make a new PR, and this will be hopefully without any merge  conflicts :)

**Comment by gbowne1** [comment]
I wonder if this might work using the github cli tool

**Pull request closed without merging**
