### PR TITLE
Minor contributions

### PR DESCRIPTION
**Pull request by dalekvim**
I'm still new to contributing, so I wanted to do something simple. Hope I didn't do anything annoying!

Changes:
- Removed the ".vs/" and ".vscode/" folders because they were giving unnecessary recommendations.
- Made some slight modifications to the prettier configurations.
- Applied those changes to the project.

### CODE REVIEW

**Review by gbowne1 — CHANGES_REQUESTED** [review]
I prefer keeping these files, because if you load the new project into your VSCode or Visual Studio, you can opt out of new extensions and settings by merely clicking a button to not accept the new extensions and settings that pops up. 

Additionally, the settings are there for people new to React development that may not have settings, extensions, etc. all set up yet.

Thoughts @manuel12 @pawel975

Thoughts @manuel12

**Review by gbowne1 — APPROVED** [review]
The new Prettier config looks good.

**Review by gbowne1 — APPROVED** [review]
The new lint and prettified changes to the files that don't have ;'s or " or ' look good to me.
Approving the linted changes.

**Review by gbowne1 — APPROVED** [review]
Approving the changes to utilities

**Comment by dalekvim** [comment]
> I prefer keeping these files, because if you load the new project into your VSCode or Visual Studio, you can opt out of new extensions and settings by merely clicking a button to not accept the new extensions and settings that pops up.
> 
> Additionally, the settings are there for people new to React development that may not have settings, extensions, etc. all set up yet.
> 
> Thoughts @manuel12 @pawel975
> 
> Thoughts @manuel12

Hi Greg,

This is a really awesome project, thanks for sharing it with the community.
About the recommendations, maybe consider trimming them a little? Right now, there are more than 20 recommendations; some which I’ve never heard of.
For example, the html and css extensions (syntax highlighting is built it, right?).
Are you really sure that they need Live Share for this project?
Also you have 6 extensions relating prettier and eslint, maybe just the two main ones are fine?

Maybe we could add a list of recommended extensions with a brief description of why they are necessary in CONTRIBUTING.md (I don’t mind doing this). I’m sure this would be more helpful since most of your contributors are unlikely to be complete beginners (they downloaded and setup node after all).

P.S. Doesn’t VSCode automatically recommend extensions for the  projects you have open?

**Comment by gbowne1** [comment]
Thank you @dalekvim . This was aimed at solving a few problems that current socials have especially in the Group and Events context.

Yes, but VSCode I have found does a really poor job at recommending extenstions especially if you have a considerable amount of extensions.  

They could be trimmed a bit, yes. 

The way it works is that you can opt out of installing any new recommended  extensions. 

There are a couple linters I recommended beyond ESLint and Prettier.  But I dont remember there being 6 of them.

Syntax highlighting iirc is not available out of the box.

I do agree that the Contributing docs need updating.. or we opt to put out a DEV.md type document which describes typical tooling for React development.  

As for Linters, I am moving away from ESLint to use quick-lint-js   i encourage people to try it and evaluate it.  Types and Typescript support is coming.

I am eventually going to bring this out to its own repo or its own GitHub org. 

If you do Slack there is a invite link in the Issue tab just click on New Issue.

We could use a couple new contributors and contributions are welcome.

**Comment by dalekvim** [comment]
Hi Greg,

That makes sense to me; do you need me to undo the commit on my end, or can you select which ones to keep?

I would also like to help incrementally convert this project to TypeScript. From the discussions, it looks like there are mixed feelings about this, but create-react-app makes this process seamless – you just have to install the appropriate dependencies and change the 'j's to 't's.

Unfortunately, it looks like the slack link is out of date…
image

**Comment by gbowne1** [comment]
I am all about new developer experience.  And enhancing the developer experience of anyone thats not a new developer. And 

This project has a long ways to go yet.  But we already have the UI done for severap features.  I'm also not in any rush to get this done. 

I do not want to exclude newer developers from contributing, and took into considering they may not have gotten their setup done other than installing their ide or editor.  We can enhance by letting them know we care about their experience with this project among other things.

**Comment by gbowne1** [comment]
Yes, undo the commit for the VS stuff.. the rest you can leave as is. 

Yes we can incrementally move towards TS.  I am not at the stage yet where I have learned it yet.  We have been getting along fine with ordinary use of prop-types, which I have found being the best experience yet.  I still want to think of people like me that havent learned yet.

We also have to think about how much of TS we actually need.  If we need a limited set of types then I would say no.

**Comment by dalekvim** [comment]
Erm… Are you a bot? Should I make an issue about the slack link?

**Comment by gbowne1** [comment]
https://join.slack.com/t/reactsocialmediadev/shared_invite/zt-1tk7dstfb-H6QeQZXdSEKQ~LnSmgnpag

A new link... but yes it needs fixed in the template.

**Comment by gbowne1** [comment]
I do not remember how to cherry pick remove commits out of a PR or commit series with git.

**Comment by dalekvim** [comment]
Done

**Review by gbowne1 — APPROVED** [review]
Approving the changes to this PR.

We should discuss any dev tooling and those particular features with the core contributors @pawel975 and @manuel12 especially so that new people can contribute in an effective manor and get running quickly.

**Comment by dalekvim** [comment]
I feel like I’m going a bit overboard on this branch.
Should I revert the typescript related commits and make a separate pull request for that?

**Comment by dalekvim** [comment]
All tests passed!
image

**Comment by manuel12** [comment]
> All tests passed! image

Just one thing to mention: these tests only cover the login component and at the current state they are incomplete(I've just submitted a PR with further tests), they do not cover other components. 

@dalekvim Looks like you changed a lot of other files. Just saying this so that you know it might take time to review this :)

**Comment by gbowne1** [comment]
@manuel12 Most of these changes are outside of the scope of the issue he was working on.  Issues need to be created for things like Refactor to Tyoescript and some of his other commit titles/descriptions. It is also a very latge PR.  We need stick to the original issue scope in a PR. Much cleaner than just adding in a bunch of random commits which do not relate to the issue.  Probaly due to the poor contributing docs. I didnt think this wouod be an issue though to be quite fair.  Comment  thoughts, etc?

**Pull request closed without merging**
