### PR TITLE
User profile UI

### PR DESCRIPTION
**Pull request by manuel12**
This PR creates  a User Profile UI defined in: https://github.com/gbowne1/reactsocialnetwork/issues/302

To check the UI just navigate to /user-profile. This just UI. No functionality has been added  apart from using existing user data to in certain parts of the UI: avatar image, username, email, etc.

For me the  UI looks like this on light mode:

image

And on dark mode:

image

### CODE REVIEW

**Comment by gbowne1** [comment]
Very nice @manuel12!

I think that definitely will give us a great place to start with.

All the values under the avatar or pic like Workplace, Location, etc should be rendered straight from the database so they are dynamic unless you want to convert those to buttons or use another tab to display all the information on a user.

Might need another couple tabs.

The avatar/pic I think needs a pencil edit icon in a small MUI badge circle.

Looks like it has a few merge conflicts.

**Comment by gbowne1** [comment]
Social Icons should use their proper colorization

**Review by pawel975 — APPROVED** [review]
Nice, great work! Approve.

**Comment by gbowne1** [comment]
Only features I would add is maybe a album/pics tab for people to post their photos/albums.. and or maybe a tab to show and/or manage the users friends

Ideas?

**Review by gbowne1 — APPROVED** [review]
- [x] checked out this change locally for testing and review for merge 
- [x] Manually reviewed browser console for errors and warnings 
- [x] Manually reviewed for syntax, grammar, spelling, etc errors

This new User Profile feature looks great.

I tested in Firefox and Chrome and ran the A11y diagnostics as well.

I didn't run the tests yet as this is only the UI.

Approving for merge! Thanks for the opportunity to review your PR and for your contribution

**Comment by manuel12** [comment]
@gbowne1 @pawel975 I've added colors classes to all social media icons:

Now they look like this:
image

**Comment by manuel12** [comment]
> Only features I would add is maybe a album/pics tab for people to post their photos/albums.. and or maybe a tab to show and/or manage the users friends
> 
> Ideas?

We will add more functionality to this page in the future and also will complete the current functionality. Here I am just completing the UI to have something to work on.

Also later I will update the User table in the database adding things like location, career, workplace.

**Pull request merged**
