### PR TITLE
Naming convention updates

### PR DESCRIPTION
**Pull request by manuel12**
This is a much needed clean up PR.

Among the things updated:

- Moving CSS imports to the top of component files.
- Updated CSS class names in components and styles files according to the `BEM` convention.
- Updated utils function  JSDocs strings.
-  Create  UI and API folders for e2e tests.
- Moved existing tests files to their respective folders.
- Updated test cases names according to the `"should do X when input Y"` convention.

### CODE REVIEW

**Comment by gbowne1** [comment]
A side issue would be to document the styling in the Wiki. We have had a couple people not really get how our styling works.  I would like to prevent people from not styling properly especially the panels and using the variables.css

**Review by gbowne1 — APPROVED** [review]
- [x] Checked out these changes locally  for testing and review for merging
- [x] Manually reviewed the browser console for additional warnings and errors
- [x] Manually reviewed the styling cases in the browser styling panel in Firefox

We still have artifact errors coming from the boilerplate App.css and index.css which would be used for global styling.  I need to make a issue to fix that.  These are webkit and moz errors showing up in Firefox. 

This is a great cleanup of the CSS and styling.

We need to continue and documenting styling.  I would also suggest adding Tailwind to help enhance MUI.

**Comment by manuel12** [comment]
> A side issue would be to document the styling in the Wiki. We have had a couple people not really get how our styling works. I would like to prevent people from not styling properly especially the panels and using the variables.css

How so? What exactly do we need to add? I can make a quick update.

**Comment by gbowne1** [comment]
@manuel12 I am gonna have a look tonight and see.

**Pull request merged**
