### PR TITLE
Update of folder structure

### PR DESCRIPTION
**Pull request by pawel975**
## Description

I noticed that we have a little bit mess in folder structure and have reorganized some things in /src directory.

`/src`

image

Every component has it's own folder with it's styles close to him. `/src/assets` is now empty. Also `/src/components` contains only widely used components.

image

`/src/layouts` contains every component that is rendered within multiple pages like `<TopNav/>` . `/src/pages` contains all pages that are rendered. Every page and layout component could contain it's own child components used only inside them, in this case this child component is nested inside with it's styles.

image

I also deleted `/src/utils.js` which contained functions affecting local storage. Those functions are now in `/src/utils` directory (previously `/src/helpers`)

image

I also deleted not used files which are similar to other, so far used. 

If it goes about testing, __tests__ directory should be close to tested component, like styles.

What do you think guys? @gbowne1 @manuel12 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manually

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by gbowne1** [comment]
Yes, the app is a bir of a mess.  I did what I tgought was best scaffholding out some project structure.

I was thinking about moving towards using a layout && page scheme.  Which is more of a MVC model view controller type of system that I think is done predominantly by Typescript or projects where there is no JSX/TSX.  Again more research is needed.

The page could inevitably be our components and the layout files organize our components.  Then you have controllers which are JS or TS which provide functionality between both.

We need to start locking down the ORM/ODM.  Id like to learn prisma.  

Oh and @pawel975  can you help fix up my ERP app?  Its a mess too??

**Review by gbowne1 — APPROVED** [review]
I am approving this change in whole as we do need significant project cleanup.  I didnt feel the need to test this yet.

**Comment by pawel975** [comment]
> Yes, the app is a bir of a mess.  I did what I tgought was best scaffholding out some project structure.
> 
> I was thinking about moving towards using a layout && page scheme.  Which is more of a MVC model view controller type of system that I think is done predominantly by Typescript or projects where there is no JSX/TSX.  Again more research is needed.
> 
> The page could inevitably be our components and the layout files organize our components.  Then you have controllers which are JS or TS which provide functionality between both.
> 
> We need to start locking down the ORM/ODM.  Id like to learn prisma.  
> 
> Oh and @pawel975  can you help fix up my ERP app?  Its a mess too??
> 
> 

I have to read about MVC model, ORM/ODM since I don't know anything about this.

Unfortunately I don't feel like contributing to both ERP and Social platform at the same time, at least at this moment. I would like to focus on one thing 😀

**Comment by gbowne1** [comment]
Fair enough @pawel975.  It really needs redone from scratch.

Object Relational Mapping (ORM) is a technique used in creating a "bridge" between object-oriented programs and, in most cases, relational databases. Put another way, you can see the ORM as the layer that connects object oriented programming (OOP) to relational databases.

ODM is Object Document Mapping. It is like an ORM for non-relational databases or distributed databases such as MongoDB.

**Comment by pawel975** [comment]
> Fair enough @pawel975.  It really needs redone from scratch.
> 
> Object Relational Mapping (ORM) is a technique used in creating a "bridge" between object-oriented programs and, in most cases, relational databases. Put another way, you can see the ORM as the layer that connects object oriented programming (OOP) to relational databases.
> 
> ODM is Object Document Mapping. It is like an ORM for non-relational databases or distributed databases such as MongoDB.

Ok, I get it, thanks!

**Review by manuel12 — APPROVED** [review]
This is great, a much needed re-structuring of files.
Approving changes, thanks!

**Comment by gbowne1** [comment]
We also have some package updates due soon.  They are minor but I wanna stay up to date.

I recall seeing sone package issues on a fresh install.

Ideas for this?

**Pull request merged**
