### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by promise-dash**
Resolved issue #185  
Updated the packages and removed the ones we are not using.

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
Approving this change for merge.  These are the correct packages.

**Review by pawel975 — APPROVED** [review]
Approve changes.

**Review by manuel12 — APPROVED** [review]
Approving changes!

**Comment by promise-dash** [comment]
Thanks for merging my PR. I'm glad to hear that my contribution was useful.

**Comment by gbowne1** [comment]
Youre welcome. We do have a few minor issues at the moment we are tryimg to get cleared up.  But it shouldnt ne too long.  Theres 34 other issues and Feature tasks to work on.  Feel free to work on anything.  

Right now we are having issues with Babel, Webpack, ESLint and Prettier.

**Pull request merged**
