### PR TITLE
Configured dependabot to update packages #294

### PR DESCRIPTION
**Pull request by balajik**
**Summary**
Configured dependabot to update the packages by weekly in client, server and e2e packages. Max of 2 PRs will be created in client/server and 1 will be created e2e if there is any new updates available.

Now, I have a configured a bare minimum dependabot setup to update the packages. We can later add or update the configuration in the dependabot.yml file.

Here is the config options for dependabot: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-the-dependabotyml-file

**Note**
As of now, we there is no option to using glob patterns or providing multiple path to the dependabot to pick the package.json in the nested folders. So for now, we have to duplicate the update config for each package folders.

Dependabot issue can be found here: https://github.com/dependabot/dependabot-core/issues/2178 https://github.com/dependabot/dependabot-core/issues/3951

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
After reviewing the documentation and the code in this PR, I believe it shall work as intended to help us keep dependencies up to date automatically.  

We can always make minor changes to this if there becomes a problem.

Approving for merge.

**Comment by gbowne1** [comment]
Not really necessary, but ok, I can. Anyone can add labels, iirc.

**Review by pawel975 — APPROVED** [review]
Looks good to me.

**Comment by gbowne1** [comment]
This should help us keep this updated without having to do a lot of extra manual work.

**Review by manuel12 — APPROVED** [review]
Great work! Approving changes.

**Pull request merged**
