### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by newdydx**
This pull request fixes the issue #26 

**I added  close [ X ] buttons that could close all the components**

### CODE REVIEW

**Review by gbowne1 — CHANGES_REQUESTED** [review]
@newdydx I have reviewed this PR. It merges every previous commit including yours into my bugfix branch not the main branch. This may cause merge conflicts.  

Your previous commit/PR would have been ok.

I will close this one and reopen the other PR.

**Comment by gbowne1** [comment]
@newdydx I can merge this to my bugfix branch but it is better if you commit PR to your local newydx:bugfix-{bugfixname} with the single commit bugfix annd then PR to gbowne1:main.  This will then eventually end up in origin:main once I merge to there.

**Comment by gbowne1** [comment]
Yes @newdydx

**Comment by newdydx** [comment]
@gbowne1 you mean like this??

bugfix

**Comment by gbowne1** [comment]
Yeah.  Thats how you should commit and PR.

**Comment by gbowne1** [comment]
Ok still conflicting with Post.jsx and Settings.jsx.  Needs some changes by committing to your local bugfix again.  Won't be able to resolve this for a while.

**Review by newdydx — COMMENTED** [review]
@gbowne1 nice

**Pull request merged**
