### PR TITLE
Friends back end

### PR DESCRIPTION
**Pull request by manuel12**
This PR includes the friendship-related  backend actions and APIs + api tests.

The added api routes are:

* Friends routes:
  * `GET /api/users/:userId/friends` -> Get all friends from a user.
  * `GET /friend-requests/received/:userId`-> Get pending friend requests received by the user.
  * `GET /friend-requests/sent/:userId`-> Get pending friend requests sent by the user.
  * `POST /api/friend-requests/`-> Send a friend  request.
  * `POST /api/friend-requests/accept/:requestId`-> Accept a friend  request.
  * `POST /api/friend-requests/reject/:requestId`-> Reject a friend  request.
  * `DELETE /friends/:friendshipId`-> Unfriend a  specific user.

### CODE REVIEW

**Review by pawel975 — APPROVED** [review]
Great job! Approved 😀

**Review by gbowne1 — APPROVED** [review]
- [x] checked out this change locally for testing and review for merge 

This adds the backend and APIs and endpoints for the friends system

This works fine.

Approving for merge

**Comment by gbowne1** [comment]
@manuel12 while I have mentioned needing at least two approvals minimumon PR's for merge, I would wait to see if @balajik would review them unless there's a specific need to merge ASAP.  Hopefully we can get some more contributors.

**Comment by manuel12** [comment]
> @manuel12 while I have mentioned needing at least two approvals minimumon PR's for merge, I would wait to see if @balajik would review them unless there's a specific need to merge ASAP. Hopefully we can get some more contributors.

Had already merged at that time but will do so for next PRs.

**Comment by gbowne1** [comment]
It's ok. I just figured at some point they would want to review.

**Pull request merged**
