### PR TITLE
Add close icon

### PR DESCRIPTION
**Pull request by manuel12**
[TODO] Close X Icon missing from other components #128

Created a CloseButton component. Replaced the old close button with CloseButton component on Dashbaord, Friends, Profile, UserProfile components. Added CloseButton to Settings component.

I think this covers all the components that needed this type of work. If I missed some please write it in a comment and I can make another commit.

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
I just got back from being out and checked out this change locally and tested.

This works as expected.  No recommended changes.  This looks really  good.

Approving for merge.  Now need to work on filling out the components panels.

**Review by pawel975 — APPROVED** [review]
Looks good to me, approve :+1:

**Comment by gbowne1** [comment]
Great work so far.   I would say we work on the first iteration of the components next.

I am working on the Friends component.

**Comment by manuel12** [comment]
> Great work so far. I would say we work on the first iteration of the components next.
> 
> I am working on the Friends component.

I agree, components next 👍

**Comment by gbowne1** [comment]
Yeah even if they are not pretty or semi functional.  We can iterate through the design.  I am totally okay with wherever they land in the first iteration. @manuel12  @pawel975 @Dylan-Clarry

**Comment by gbowne1** [comment]
@manuel12 everyone I showed the login screen to loved it.  It got 26 hearts

**Pull request merged**
