### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by meleneth**
Probably not a great idea to actually merge this, but it builds containers for the client and the server.

Probably doesn't configured the mongodb to actually be connected

ports for the running services are also probably wrong

... but it builds, something

docker compose build

### CODE REVIEW

**Comment by gbowne1** [comment]
I think it would be ok to Dockerize this by merging this PR. 

That being said even if you left out the docker stuff it fixes a few minor issues.

I will review this.  I've added the other collaborators /maintainers.  Thanks for the PR @meleneth

**Review by gbowne1 — APPROVED** [review]
- [x] checked out this change locally for review and testing for merge 
- [x] assigned other collaborators/maintainers to review 
- [x] manually reviewed code for possible issues 

Thrs PR introduces Dockerization to the reactsocialnetwork project.

The Docker config in this PR may need slight adjustment but it seems to be good  and well written.

I believe we can merge this PR as is with little to no consequence and we should look into this being a permanent thing.

Approving this PR for merge ASIS.

**Review by manuel12 — APPROVED** [review]
Approving changes!

**Comment by gbowne1** [comment]
Approving new changes/additions via commit

**Comment by gbowne1** [comment]
Merging this asis.

**Pull request merged**
