### PR TITLE
Adding a profile image preview

### PR DESCRIPTION
**Pull request by dimassibassem**
I would like to contribute to this project. This is my first pull request, and I plan to submit more in the future.

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
Checked out this change for testing locally as part of Profile updates.

No screenshots were provided of working changes.

Other than that, this looks fine and will need testing prior to merge. It appears to work fine without adding additional errors to the app.

@dimassibassem Do you have screenshots of your changes here to add so we can see?

Approving for merge.

Thank you for the opportunity to review your PR and we welcome any contributions.

**Review by manuel12 — APPROVED** [review]
@gbowne1 Changes add a profile picture preview to profile page, like so:

image

Approving changes :)

**Review by gbowne1 — CHANGES_REQUESTED** [review]
@dimassibassem

Just so that you are aware, We have decided not to use Vite, pnpm, etc with this project at this time.

The new commit is beyond the scope of the original PR you made was originally for the Profile.jsx 

 If you wish to submit this sort of change, Please make an new issue for this and we will discuss possible implementation.  If not, you can make a discussion for this in Discussion

**Comment by dimassibassem** [comment]
@gbowne1 
Thank you for informing me about the decision regarding the project's tooling. I understand that Vite, pnpm, and similar tools will not be used at this time.

Regarding the new commit, I apologize for going beyond the scope of the original pull request, which was initially for the Profile.jsx file. If you would like me to submit this type of change, I can create a new issue to initiate a discussion on its possible implementation.

**Comment by gbowne1** [comment]
Yes, I particularly would request you make a issue and or a discussion.  This type large scale changes like this need to be discussed with the project leads and maintainers.

@manuel12 @pawel975 and myself @gbowne1 

To anyone wishing to make medium and large scale changes especially changes to different package managers and build/test systems or moving away from create react app we ask that a discussion and/or issue be created with any relevant code or browser based issues and not to go beyond scope of an issue.  Please report any bugs, errors, warnings, etc you find individually and we can address them one at a time.  

If this was not made clear in the contribution documents this might need some clarification.

Thank you @dimassibassem

**Pull request closed without merging**
