### PR TITLE
BUG: propTypes Issue

### LINKED ISSUE #275: [Bug]: Panel and Friends.jsx prop types issue
### Describe the Bug

The two errors that exist in Friends.jsx through using Panel were:

Warning: Failed prop type: The prop children is marked as required in Friends, but its value is undefined.

and also

Warning: Failed prop type: Invalid prop children of type array supplied to Panel, expected object.  

There may also be other issues related to this.

### Steps to Reproduce

Start the server and client.

Errors and other warnings will be present in the browser console.

### Screenshots

_No response_

### Which device are you using?

Linux VM

### Which operating system are you using?

Linux Debian base

### Which browser are you using?

Firefox 112

### Additional Context

_No response_

### Contribute

- [ ] I am willing to contribute and submit a pull request

### PR DESCRIPTION
**Pull request by NigamDevansh**
Fixed #275

### CODE REVIEW

**Review by pawel975 — APPROVED** [review]

**Review by gbowne1 — APPROVED** [review]
Checked out this change locally for testing. It appears that this change fixes the issue with Friends.jsx with respect to the Panel component prop types.

Approving for merge.

**Comment by manuel12** [comment]
@NigamDevansh Hello :) did you run the e2e tests after this change to Panel component?

**Comment by gbowne1** [comment]
@manuel12 Do we have anything that catches bad prop types, especially for child/children?

**Comment by manuel12** [comment]
@gbowne1 No we don't have check to test specifically for props. I was just asking to make sure the Panel component was working well after the changes.

**Comment by NigamDevansh** [comment]
@manuel12 hi ! yes i ran all the tests and it failed `src/pages/Events/SingleEvent/__test__/SingleEvent-initial-state.test.js` this one

**Comment by manuel12** [comment]
> @manuel12 hi ! yes i ran all the tests and it failed `src/pages/Events/SingleEvent/__test__/SingleEvent-initial-state.test.js` just this one

Ok thanks :)

**Review by manuel12 — APPROVED** [review]

**Pull request merged**
