### PR TITLE
Login Page theme and UI changes

### PR DESCRIPTION
**Pull request by pratham2609**

### CODE REVIEW

**Comment by gbowne1** [comment]
@pratham2609 can you please provide some screenshots of your changes and some description of what you changed and let us know why or link an issue to this PR?

Thank you.

**Review by pawel975 — APPROVED** [review]

**Review by manuel12 — CHANGES_REQUESTED** [review]
Hello. I see that many of the naming of the newly added CSS variables does not follow our current naming convention. Please check: https://github.com/gbowne1/reactsocialnetwork/wiki/Developer-Guide#css
to see how to name CSS variables.

**Comment by manuel12** [comment]
> @pratham2609 can you please provide some screenshots of your changes and some description of what you changed and let us know why or link an issue to this PR?
> 
> Thank you.

As @gbowne1 would be good to  see some screenshots of the UI changes in both light and dark mode :)

**Comment by pratham2609** [comment]
Sure i will check it!

**Comment by pratham2609** [comment]
I am not having my laptop right now. I will share them with you as soon as
I can

**Comment by pratham2609** [comment]
I did the UI changes in login/register form page.
Here are the screenshots of the same.
There was not any issue but theme was not attractive at all along with the
button should be on the top right of the screen.

**Comment by gbowne1** [comment]
@pratham2609 

The screenshots did not show up in your last post in this thread.

**Comment by pratham2609** [comment]
Here are the screenshots 
If you want t
IMG_0546
o change the colors just let me know
IMG_0545

**Review by gbowne1 — COMMENTED** [review]
To be honest, I am not fond of this login page using those colors.  We do still need to define a color set, or do we provide a way for the user to change the coloroization of the app to their liking.

I also don't see any reason to move the light/dark mode controls to the corner.

I will wait on approving this to hear from the other collaborators 

@pawel975 @manuel12 @balajik

**Comment by manuel12** [comment]
@gbowne1 @pratham2609 I wouldn't mind leaving the colors like this for now till we decide on a color palette but in any case  there are conflicts on `Terms.jsx` that need to be resolved.

**Review by manuel12 — CHANGES_REQUESTED** [review]
Please solve conflicts  on `Terms.jsx`.

**Review by gbowne1 — APPROVED** [review]
Approving for merge with comments:

- Need to redefine the color pallet using variables.css
- Font change?
- Login.jsx has a LOT of padded blocks of code in it

**Review by manuel12 — APPROVED** [review]
Approving changes!

**Pull request merged**
