### PR TITLE
Add Timeline and Posts.

### PR DESCRIPTION
**Pull request by manuel12**
This is a pretty big PR that adds a timeline page on home( instead of the dashboard we had before) and adds a PostForm on top of that Timeline and Posts to fill it in.

Just load the page and go to home. If you are anywhere else in the page just click on the "LOGO" text on the topbar and you will be redirected to the home page.

In order to create a post just write something on the post and click the submit button.

Right now the posts do not accept images videos or moods. And also all posts  right now will use my profile image and 
picture.

I also created a backend and routes and tests for posts.

All tests pass on my side :) so it should be pretty straight forward to review.

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
Checked out this large PR locally for testing, as part of the post functcionailty. 

This appears to work correctly.  Previously navigating to /post didn't do much of anything and / displayed the dashboard.  

Now we can work out what we want in the main, root view.  This is great so far.  Good job @manuel12

**Comment by manuel12** [comment]
Could we have this reviewed guys? I need this merge to add some more things on top :)

**Comment by gbowne1** [comment]
@manuel12 

If the e2e and other tests pass, I would be ok with merging some things without additional review so as long as they do not intruduce breaking changes just so we can keep things moving along, especially if you are having to work on top of them.

**Comment by gbowne1** [comment]
@manuel12

I forgot to mention that in PostForm.jsx there is a duplicate key ` method: "POST", ` on line 30.  Line 29 and 30 are the same

**Pull request merged**
