### PR TITLE
Add panel to create events

### PR DESCRIPTION
**Pull request by manuel12**
Fixes https://github.com/gbowne1/reactsocialnetwork/issues/133

I've added a Create New Event button and  an event attendance filter, with which we can filter events by different levels of attendance(Going, Interested, Not Going).

I've also added an attendance select dropdown to each event, where the user can select his preferred attendance or update the
attendance of an event.

I've also added share and delete buttons to each event, the share button does nothing right now, we need to decide on how this should work. The delete button is working and deletes the event.

As previously discussed I added the Create New Event button and  an Event attendance filter on the events component directly and not in a SideBar.

I've also added the the Create Event modal, which appears when clicking on the Create New Event button. I've added validation and datepicker to such component.

This is how events dashboard looks:

image

How create event modal looks:

image

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
I checked out this change and tested it locally.  I am approving this change for merge.  This change with enhancements to the Events component appears to work as intended.  

I like this implementaton. It may not need much further work.  Thanks @manuel12 for the opportunity to review this PR  :smile:

**Comment by gbowne1** [comment]
My only concerns is that:

- No way to set event as Private or Public Event
- No Start and End time set
- Check mark for reoccurring event
- Google Maps pin location
- Some way to edit or reschedule events.  Would close the event but push notications to event subscribers that the event was changed.

This/these probably would need a new issue is that ok? @manuel12 @pawel975 @Dylan-Clarry ?

That is still quite a bit of white space between the event picture and the buttons on the right side of the event.

**Comment by manuel12** [comment]
Yes, it would be great to create separate issues for each.

Also would be great to add user stories to the tickets from the beginning in order to document the all functionality we need. We can always look at the FB UI but, do we want to make a copy of FB? Maybe we want somethings they have and some they don't.

As for things like the amount of white space in each event element, or marks for reoccurring events, or google map pin and other UI additions, it would be great to also have wireframes added to the issues. This way we can be very specific on how UI should look, which UI features to add and where to add them.

A great, free tool to make wireframes is https://www.figma.com/
I've used it many times and it works like a charm :)

**Comment by gbowne1** [comment]
Well, I could just add a `- [ ]` which would allow someone to turn the individual items into issues by hovering  then clicking on the circle on the right that comes up when you click on the [ ] in GitHub.

I created that issue.

Should we create an issue for a Figma design based on what we have already, then we could work from there?  I'm terrible at wireframing.  

@pawel975 @manuel12 @Dylan-Clarry

**Review by pawel975 — APPROVED** [review]
I clicked through Events and really like your work @manuel12 . Aprove changes and sorry for reviewing so late :)

**Comment by gbowne1** [comment]
Thanks @pawel975! I really loved the changes!  Merging.

**Pull request merged**
