### PR TITLE
Update of Settings.jsx component

### LINKED ISSUE #40: [CSS] Fix the Settings.jsx component
Describe the bug
There are several things wrong with the Settings.jsx component, which include contrast ratio problems for accessiblity.

These are the `<h3>`'s and the `<div>`s for the section container.

To Reproduce

Run the dev server with `npm start` in the root dir. May need to `npm i` or `npm install` the app as I did not include my local node_modules dir. in the upload and it is in the .gitignore.

Expected behavior
Screen reader accessibility

Desktop (please complete the following information):

    Linux, x64
    Firefox, Chrome
    both 107

Additional context

### PR DESCRIPTION
**Pull request by pawel975**
## Description

@gbowne1 

I fixed accesibility by changing main text color to more contrasting one (I did for whole app, because problem was the same on every page) and by including tabbable switches from MUI.
Also changed Settings.jsx component structure to better aligned.

image

Fixes #40

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manually

**Test Configuration**:

- Hardware: ----

- Operating System: ----

- Toolchain: ----

- Browser: ----

- SDK: ----

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
I checked out and tesed these changes locally.  They all appear to work fine.  
Settings component will need some more work, but this is fine for initial work on the  component panel.

Good to see the changes to a11y as well.  

I would work on building a theme controller instead of each component, but this is great work.  Thanks for the opportunity to review this PR and commits. @pawel975 

Approving all changes for merge and merging.

**Review by gbowne1 — APPROVED** [review]
Second commit looks good as well.  Are we toggling theme on all components now?
Approving 2nd commit.

**Review by gbowne1 — APPROVED** [review]
Yeah, I am behind on my merge to main.  I've been waiting on enough significant work on this to merge.

**Review by gbowne1 — APPROVED** [review]
As far as updating contribuors I need to move all contributors to:
- AUTHORS.md
- CONTRIBUTORS.md
- CODEOWNERS
- ACKNOWLEDGEMENTS.md

and any other files.

**Comment by pawel975** [comment]
> Second commit looks good as well. Are we toggling theme on all components now? Approving 2nd commit.

I see only top nav don't change on theme change, it's light grey all the time.

**Comment by gbowne1** [comment]
Yeah, the app doesn't theme change for everything that should change.  This needs some work.

In dark mode, just about everything should be some form of black, gray, white.  Light mode should have more colors (have not decied on them yet..  but thoughts suggest blue which is a quite common theme color on many apps.

**Comment by pawel975** [comment]
Blue should fit both dark and light theme so I think it's good idea 😀

**Comment by gbowne1** [comment]
Yeah, both can have some blue in it.

**Pull request merged**
