### PR TITLE
Feedback modal

### LINKED ISSUE #125: [TODO] Add a Feedback
**Is your feature request related to a problem? Please describe.**
Add a Feedback modal accessible from the Feedback in the user icon in the topbar.  Not sure where this would route.  /feedback maybe?

**Describe the solution you'd like**
Not entirely sure what would be best here.  But seems like an expandable modal might work.  User might just want to either:
 1) Contact about suggestions for improvements (done through GitHub?)
 2) Contact about something that went wrong (bug?)
Insert GitHub link

**Describe alternatives you've considered**
Feedback pops up from lower portion of page (maybe in mobile)?

**Additional context**

### PR DESCRIPTION
**Pull request by pawel975**
## Description

I created feedback modal which is accessible on /feedback route. Modal is on top of the rest of app and has two buttons (`Go back`, `Go to GitHub`) and link to contribute documentation. Also added few fixes in app to match this solution.

`Go back` - switches route to previous one
`Go to GitHub` - leads to project repository, link opens in new tab, first tab stays the same with modal open.

Fixes #125

image

image

image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manually

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
I checked out and tested this change locally.  

This appears to work just fine as a part of the Help & Feedback system initial work.  

If we need to add a email address in the future that will be easy to do.  But I feel like in-app features work the best over outside resources.

**Review by gbowne1 — APPROVED** [review]
This change checks out good.  It appears a little bit quicker too in Chrome.

Approving this commit for merging.

**Review by gbowne1 — APPROVED** [review]
Approving the new changes to this code cleanup and CSS commit for merging.

**Review by manuel12 — APPROVED** [review]
All looks good to me. Approving changes.

**Pull request merged**
