### PR TITLE
Fixed #282 and #281 - added beginning of the friendship-related backend.

### LINKED ISSUE #281: [feature]: Make it possible for user to set a profile image url.
### Is your feature request related to a problem? Please describe.

User should be able to set a profile image url on `/profile.` This  way each post could have a personalized image instead of having mine. 

### Describe the solution you would like

I will implement and add tests for this.

### Describe the alternatives you have tried

.

### Additional context

_No response_

### LINKED ISSUE #282: [feature]: Make sure username is displayed in posts
### Is your feature request related to a problem? Please describe.

Right now my username is displayed in all posts. We should make it so the current user's username be used instead.

### Describe the solution you would like

I will implement this and make tests.

### Describe the alternatives you have tried

.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by manuel12**
With this commit I've fixed #281 and #282. Now username and user account image will be displayed when a user creates a post.

In order to update the avatar image you need to go to /profile and add an image url on the Profile Image Url field and press "Create".

The current UI on /profile is not very good and needs to be updated:

image

I will create a ticket for this and assigned to myself.

I've also added tests for both username and profile image url checks.

In the commits are also the beginning of the backend for the friendship functionality I was working on. With this users can send friend requests between each other. I will commit the remaining  changes in another PR.

### CODE REVIEW

**Comment by manuel12** [comment]
I've also run all cypress tests and they all pass for me:

image

**Comment by gbowne1** [comment]
It's ok. I created bunch of labels recently.  And while everyone has been busy, I have been working on other things to get this ready.

**Review by gbowne1 — APPROVED** [review]
- [x] Checked out this change locally for testing and review for merge

This looks great as the initial friends system backend.  I will need to do some more testing with this in development mode.  It appears to work properly without causing adverse affects to other parts of the app.

Approving for merge.  Thank you for the opportunity to review your PR and for your contribution @manuel12

**Comment by manuel12** [comment]
> * [x]  Checked out this change locally for testing and review for merge
> 
> This looks great as the initial friends system backend. I will need to do some more testing with this in development mode. It appears to work properly without causing adverse affects to other parts of the app.
> 
> Approving for merge. Thank you for the opportunity to review your PR and for your contribution @manuel12

Glad to be contributing again!

**Comment by gbowne1** [comment]
@manuel12 seems to be some merge conflicts now.

**Pull request merged**
