### PR TITLE
Creation of CONTRIBUTING.French.md

### PR DESCRIPTION
**Pull request by DavidGomes77**
This is the french version of CONTRIBUTING.md.

Titel: CONTRIBUTING.French.md

### CODE REVIEW

**Review by pawel975 — APPROVED** [review]

**Comment by gbowne1** [comment]
@DavidGomes77 This PR (and the other PR's you created) actually remove the english CONTRIBUTING.md please leave the original english language CONTRIBUTING.md intact and just PR the file.  You could have contributed all the files in a single PR, but this is fine.

**Review by gbowne1 — CHANGES_REQUESTED** [review]
Add back the original CONTRIBUTING.md in english.  No need to remove this. Just add the new CONTRIBUTING.French.md 

Approving, except for this

**Review by manuel12 — CHANGES_REQUESTED** [review]
It seems the original CONTRIBUTING.md was deleted. It should not be.

**Comment by gbowne1** [comment]
This is unlikely to get fixed by the user who issued the PR 

Suggest closing this PR @manuel12 @pawel975 and the other two as well.

**Comment by manuel12** [comment]
Agreed, better to close.

**Pull request closed without merging**
