### PR TITLE
Fixed padding and float issue of footer and header

### PR DESCRIPTION
**Pull request by MihirRajChowdhury**

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
This change lools good and will fix issues with responsiveness.

**Comment by gbowne1** [comment]
Hmm needs some comflicts resolved in App.css and Footer.css

**Review by gbowne1 — APPROVED** [review]
Approving these  changes  for merge as resolved conflicts.

**Review by gbowne1 — APPROVED** [review]

**Review by gbowne1 — APPROVED** [review]

**Review by gbowne1 — APPROVED** [review]
This change is approved for merging.

**Comment by gbowne1** [comment]
Hmm.. Still not allowing merge.

**Comment by MihirRajChowdhury** [comment]
I tried making changes again but if it doesn't merge can you please suggest what I can do to get it merge

**Review by gbowne1 — APPROVED** [review]
Approving these changes for merging to resolve merge conflict.

**Comment by gbowne1** [comment]
Still will not merge 😶

**Comment by gbowne1** [comment]
> I tried making changes again but if it doesn't merge can you please suggest what I can do to get it merge

Well..  I don't know.  It's definitely not merging.  I did not notice anything out of the ordinary that would keep it from merging.  

Might need to roll back your local main to a state before these changes and do all of the changes you made before all at once. 

I'm no expert on merge conflicts either.

**Comment by MihirRajChowdhury** [comment]
ok then I will try to fork the repo again and try to make the changes in the new repo

**Pull request closed without merging**
