### PR TITLE
Fixed theme reseting on reload

### LINKED ISSUE #138: [BUG] Theme mode resets on reloads
**Describe the bug**

As title says.

**To Reproduce**
1. Go to '/'
2. Click on theme switch to switch to dark mode
3. Go to "Events"
4. See that theme resets to light mode.

**Expected behavior**

App state should remember theme mode on reloads, possibly we can save it in local storage.

### PR DESCRIPTION
**Pull request by pawel975**
## Description

Fixed theme reset on reload, now theme is saved to localstorage and we can easily switch between routes.

Fixes #138

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manually

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
Checked out this change.  This seems to work fine, changing and persisting the theme through route changes.  Approving this change.

I would eventually see if we can detect the users device theme preference.  I believe there is an API for that.

**Comment by pawel975** [comment]
> Checked out this change. This seems to work fine, changing and persisting the theme through route changes. Approving this change.
> 
> I would eventually see if we can detect the users device theme preference. I believe there is an API for that.

Greate idea, we should create issue for this device theme detecting feature.

**Comment by gbowne1** [comment]
yeah I was just thinking about that the other day.  Definitely a future implementation.

**Comment by gbowne1** [comment]
I am pretty sure its just a media query.. such as 

In case user preference is light:

```css
/* Light mode */
@media (prefers-color-scheme: light) {
    body {
        background-color: white;
        color: black;
    }
}
```

In case user preference is dark:

```css
/* Dark mode */
@media (prefers-color-scheme: dark) {
    body {
        background-color: black;
        color: white;
    }
}
```

**Comment by gbowne1** [comment]
@pawel975 

This now has some conflicts with package-lock.json so unable to merge.  I suggest we add package-lock.json to a .gitignore.  This may fix sone installability problems.  I also wonder if we could get away with listing package nanes in the package.json as 'packagename@latest' instead of a version number.

**Comment by pawel975** [comment]
> @pawel975 
> 
> This now has some conflicts with package-lock.json so unable to merge.  I suggest we add package-lock.json to a .gitignore.  This may fix sone installability problems.  I also wonder if we could get away with listing package nanes in the package.json as 'packagename@latest' instead of a version number.  

Ok, I will check it.

**Comment by gbowne1** [comment]
I left this conversation on Slack too

**Review by gbowne1 — APPROVED** [review]

**Comment by pawel975** [comment]
I resolved conflicts in package-lock.json without ignoring it based on this article - https://dev.to/adamklein/package-lock-json-in-git-or-not-50l5

Would you like to tell me what do you think about it? @gbowne1

**Review by gbowne1 — APPROVED** [review]
Yeah, that appears to have fixed it. Thanks @pawel975 

I'm on the fence about adding package-lock to the gitignore or removing the file from tracking.  It's hard to say without further testing and research but this has fixed it.

Approving and Merging as fixed.

**Pull request merged**
