### PR TITLE
Added icons and menu items to dropdown menu.

### PR DESCRIPTION
**Pull request by manuel12**
Imported icons.
Added functions to handle the click of
menu items. Added styles for menu icons.

### CODE REVIEW

**Comment by gbowne1** [comment]
Please review @pawel975 

Going forwards very soon, I believe it will be beneficial to  need two reviews for merging.  We can assign appropriste CodeOwners per the CODEOWNERS guidelines

**Comment by manuel12** [comment]
@gbowne1 Thanks for the collaborator access! Before I could not do things like assign people to issues or adding milestones or projects to them. I will be sure to do it from now on.

**Review by gbowne1 — APPROVED** [review]
Checked out this change locally and tested this.

This looks good.  Works as this PR describes.

Approving this change for merging.


We will work on login/logout soon.

**Comment by gbowne1** [comment]
@manuel12 

Youre welcome. You have reached the level of contributions merged required for contributor access. (Right now, this is 5 successful merges to the project).

We will require a minimum of 2 reviews to merge very soon.  This needs to be added to the developer and contributing documententation.

Will work on some of this today while I come up with ideas to fix the ERP/MRP project which is messed up.

**Pull request merged**
