### PR TITLE
Bugfix/#285

### LINKED ISSUE #285: [Bug]: Re-lint the App's files
### Describe the Bug

It's apparent that the linting and prettier has not been done for quite a while. There are still a number of eslint issues.

run "npm run format" and "npm run lint" 

ESLint counted 
 
✖ 55 problems (49 errors, 6 warnings)
  8 errors and 0 warnings potentially fixable with the `--fix` option.
  
  after I ran lint in the client.

running "npm run format" changed 20 items.

### Steps to Reproduce

run "npm run format" and "npm run lint" 

### Screenshots

_No response_

### Which device are you using?

Linux VM

### Which operating system are you using?

Linux x64, Debian 11 Base

### Which browser are you using?

Firefox 112

### Additional Context

I will be making a separate PR to fix the linting configuration and adding lint script so that ESlint can run not just prettier.

### Contribute

- [ ] I am willing to contribute and submit a pull request

### PR DESCRIPTION
**Pull request by balajik**
Fixed #285 

**Prettier:**
1268 problems (1268 errors, 0 warnings)
1268 errors and 0 warnings potentially fixable with the `--fix` option.

All the formatting issues has been fixed.

**Eslint**
55 problems (49 errors, 6 warnings)
8 errors and 0 warnings potentially fixable with the `--fix` option.

11 easily fixable lint error has been fixed.

Below are pending issues count and Eslint rule which cause that error. 
44 problems (41 errors, 3 warnings)

- Avoid wrapping Testing Library util calls in `act` (testing-library/no-unnecessary-act)
- Avoid direct Node access. Prefer using the methods from Testing Library (testing-library/no-node-access)
- Assign array to a variable before exporting as module default (import/no-anonymous-default-export)

Need to confirm about these errors how to fix it.

**Note:**
I have run `npm run test` and one of the test case is failing already on this file client/src/pages/Events/SingleEvent/__test__/SingleEvent-initial-state.test.js

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- [x] Checked out this change locally for testing and review for merge
- [x] Ran Jest tests locally to check for passing tests

Looks like the Prettier format went pretty well, other than it increated the line count of a number of the files.

This also seems to have fixed a couple of the errors I had seen before.

Approving this change for merge.  Thank you for the opportunity to review your PR for merge @balajik and thank you for contributing.  You are more than welcome to work on other issues, please feel free to do so.

**Comment by gbowne1** [comment]
I hadn't seen any merge conflicts.. but all looks good now, thanks!  :)

**Comment by gbowne1** [comment]
ah.. I still didn't see GitHub flag a merge conflict though. usually its in the UI on here.

**Comment by gbowne1** [comment]
ah, must have missed it.  This morning Manuel merged so yeah.  I was away till evening.

**Review by manuel12 — APPROVED** [review]
Great work. Approving changes!

**Pull request merged**
