### PR TITLE
This commit adds minor changes to Friends.jsx

### PR DESCRIPTION
**Pull request by gbowne1**
I had some problems with the code in this component, especially adding cards to the Friends component panel so this 
will need quite a bit of work.  

My problems were trying to get cards to be 200px wide x 350px high total with 5-6 cards per row.  I was only able to get one card.

I removed the Suggested Friends and Friends Request panel in this commit/PR cycle.  Perhaps we can add other 

Includes removing other panels from within the coponent.

If anyone has any other suggestions on how to add cards.

### CODE REVIEW

**Comment by pawel975** [comment]
I copied this component source code to my local machine and run. I see that are some styling issues of component header. It's not different than app background.

image

@gbowne1 how do you run PR code locally to check changes?

**Comment by gbowne1** [comment]
I follow this for checking out and testing PR's locally. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally. 

 I did not change the CSS of this component.  I tried doing this component in several ways, but felt it did not make sense and would not look too good with the 3 sections of this component visible in the component at all times.  At the end the only thing that worked was a single panel in the component but it would not let me put the cards next to each other in a row.  If I put in another div it moved the new card down one row.

**Comment by pawel975** [comment]
> I follow this for checking out and testing PR's locally. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally.
> 
> I did not change the CSS of this component. I tried doing this component in several ways, but felt it did not make sense and would not look too good with the 3 sections of this component visible in the component at all times. At the end the only thing that worked was a single panel in the component but it would not let me put the cards next to each other in a row. If I put in another div it moved the new card down one row.

image

image

Is this solves the problem? It's hard to set it equal gaps when last row has less elements.

**Comment by pawel975** [comment]
We supposed to merge this PR now and I'll create my PR and resolve conflicts?

**Comment by gbowne1** [comment]
Yes @pawel975.  I would merge now.  I can finish the component.  I wanted to add images too from one of the APIs

**Comment by pawel975** [comment]
So after you will finish I supposed to fix alignment according to picture above?

**Comment by gbowne1** [comment]
Yeah then after you fix alignment I will fix colors and CSS.

Cards should be about 200x350 where the pic is 200x200.


I will add pics too.  We should look at using a random user API.

**Pull request merged**
