### PR TITLE
Update profile UI

### PR DESCRIPTION
**Pull request by manuel12**
I've updated the /profile Profile.jsx component UI. Now it looks like this on light mode:

image

And on dark mode:

image

I've also formatted code on some js files. Updated some tests and removed some repeated routes files.

### CODE REVIEW

**Comment by gbowne1** [comment]
I agree that much better but really think it needs a round avatar image.. and something more like: 

https://codesandbox.io/s/profile-page-ooh16

expand the preview

**Review by gbowne1 — APPROVED** [review]
- [x] Checked out this change locally for testing and review for merging
- [x] Manually reviewed for syntax, spelling, grammar, etc. errors
- [x] Manually checked browser console for errors
- [x] Ran Jest and Cypress tests

Doesn't appear to cause any new warnings in browser console when navigated to the profile page.

Approving this PR for merging! Thank you for your contribution and the opportunity to review your PR.

**Comment by gbowne1** [comment]
My thought was also something like this, with some modification..
UserProfile

**Comment by manuel12** [comment]
> My thought was also something like this, with some modification.. UserProfile

I can definetely update to a layout like this.

**Comment by gbowne1** [comment]
Great! :-)

**Comment by gbowne1** [comment]
I also forgot to add a friends list tab (and a couple other things) but I would guess you get the idea.

**Comment by gbowne1** [comment]
could we also make different size "Panel" components/pages, including one for mobile view?

I thought I made an issue for that

**Comment by manuel12** [comment]
> could we also make different size "Panel" components/pages, including one for mobile view?
> 
> I thought I made an issue for that

Yes definitely  At some point we will have to some breakpoints and with this the different screens and panels will resize correctly on different screen sizes.

**Comment by gbowne1** [comment]
although the breakpoints work fine, I think we could at some point add different size reusable Panel component(s).

**Review by gbowne1 — APPROVED** [review]
- [x] checked out this change locally for testing and review for merge
- [x] manually reviewed browser console for errors

This change fixes up the profile.

Approving for merge.

**Pull request merged**
