### PR TITLE
fixed contributors markdown file table; added a very important name to the list

### PR DESCRIPTION
**Pull request by Dylan-Clarry**
Fixed contributors markdown file table; added a very important name to the list...

I think it's ok that I did this without raising an issue first? I guess we'll find out...

### CODE REVIEW

**Comment by gbowne1** [comment]
Yeah this list needs updated. I will do this in the next one I do.  I thought it was pretty clear from the CONTRIBUTING that people need to update the list but it is ok as a separate PR.

There are also AUTHORS, CODEOWNERS, CONTRIBUTORS, etc. Markdown.. they all do similar things.  

My flow right now is those with 5 or more merged PR's get added to the collaborators in the Settings menu.

**Review by gbowne1 — APPROVED** [review]
Approving this contributor.

**Comment by Dylan-Clarry** [comment]
Thanks for the clarification, I made it a separate PR only because I forgot to go back and read that documentation before my first PR :]

**Comment by gbowne1** [comment]
No worries. I will be adding more to the docs.  I just figured to make it easy on everyone involved.

**Pull request merged**
