### PR TITLE
Login page labels dark mode

### PR DESCRIPTION
**Pull request by manuel12**
Fixes Login page input labels missing proper contrast on dark mode. #140

Screens look like this now on dark mode:

image

And light mode:

image

### CODE REVIEW

**Review by pawel975 — APPROVED** [review]
Looks good to me, approved!

**Review by gbowne1 — APPROVED** [review]
I checked out this change locally and tested.  Great usage of CSS.  sx sizing does not need to be done unless we have multiple view sizes locked down.  

Approving this change for merge.

**Comment by gbowne1** [comment]
@manuel12 did you get the Slack invite?

**Comment by manuel12** [comment]
> @manuel12 did you get the Slack invite?

Yes I have :)

**Pull request merged**
