### PR TITLE
[Bug]: Fix the Help component's CSS #230

### PR DESCRIPTION
**Pull request by NigamDevansh**
Fixed Issue #230 

Here are the screenshots:-

### CODE REVIEW

**Comment by gbowne1** [comment]
Much better! Thanks! We require a minimum of 2 reviews for merging.  If you would like to contribute further, this is our contributing documentation.

<https://github.com/gbowne1/reactsocialnetwork/blob/main/docs/CONTRIBUTING.md>

**Comment by NigamDevansh** [comment]
Yes will contribute more for sure.

**Review by gbowne1 — APPROVED** [review]
I have checked out this change for testing locally.  It appears to correct the CSS of the panel in Help.  

Approving for merge. 

Thank you for the opportunity to review your PR.

**Review by pawel975 — APPROVED** [review]

**Review by manuel12 — CHANGES_REQUESTED** [review]
Hello. I see that your changes actually delete some sections of the Panel .jsx and Panel.css files. I think we can get the desired results without deleting that much of the Panel files.

The issue in case is  twofold:


1.  The panel is 100% width, and it touches this edges on the screen. This is because in HelpCenter.jsx , line 68, Panel component width prop is set to 100, if you set it to 75 percent you will get the desired size. 
2. The other issue is about the Panel header not extending as far as the panel itself, for this your change of removing the max-width: 1384px rule seems to work, so you can leave it in.

Please restore both Panel.jsx and Panel.css to how they were previously, with the only exception of removing the max-wdith rule from .Panel__header on Panel.css. Then in HelpCenter.jsx change  Panel's width prop from 100 to 75.

This should solve all the issues hopefully :)

**Comment by NigamDevansh** [comment]
@manuel12  so sorry I have done the necessary changes in the PR please have a look.
@gbowne1  @pawel975

**Review by manuel12 — APPROVED** [review]
Well done! Approving changes :)

**Comment by NigamDevansh** [comment]
Thank you for being first open source contribution. :)

**Pull request merged**
