### PR TITLE
Fixing prettier errors in jsx

### PR DESCRIPTION
**Pull request by gbowne1**
This commit fixes all of the Prettier errors in the JSX.

Also moves the reduntant ESLint extends over to package.json

I saw that the ESLint configuration has "extends" in both the package.json and the .eslintrc file.  So I just moved everything from the extends over to package.json and removed the duplicate entries.

At least on my end, this change does not break ESLint.

### CODE REVIEW

**Review by manuel12 — COMMENTED** [review]
I get the following issue:

image

@gbowne1  Did it work for you locally?

**Comment by gbowne1** [comment]
@manuel12 It never even mentioned that error locally, so I don't know.

**Comment by gbowne1** [comment]
Yeah. @manuel12   I have had plenty of issues with ESLint doing oddball things.  

Although its still installed I no longer use it.  

Quick Lint doesnt require plugins for react

**Review by manuel12 — APPROVED** [review]
@gbowne1 Ok, I will approve changes then.

**Comment by gbowne1** [comment]
I am still getting a ton of errors regaurding React in scope in JSX.  I have not yet figured out what will fix that.  Ive tried turning the jsx stuff on and off.  Still get the errors.

**Comment by gbowne1** [comment]
I did actually set that incorrectly.  I will add a change to "1 = warn" as it states in that error message.  there is no "on".

**Comment by manuel12** [comment]
> I did actually set that incorrectly. I will add a change to "1 = warn" as it states in that error message. there is no "on".

Thanks!

**Comment by gbowne1** [comment]
@manuel12 you're welcome.  I think we are about all settled with this ESLint config stuff.  Time to move on to actually working on features etc.

**Comment by pawel975** [comment]
I think we should get rid of this eslint config and set only relevant rules. I think it's overcomplicated. Setting things in prettier would do the work by changing code in terms of rules instead of warning. BTW, @gbowne1 you didn't run `npm run format` command and it highlightes errors. Running this command would fix this.

image

**Comment by gbowne1** [comment]
@pawel975 

I agree we should get rid of the config and only use relevant rules. Its very overcomplicated.

Yes I did not run the npm run format command.

I have Prettier and ESLint locally also have installed the extensions. As far as I could tell, its formatting and linting and prettifying properly.  I can still try that thought.

**Comment by gbowne1** [comment]
Not completely sure what to do about this PR.

**Comment by pawel975** [comment]
I would get rid of "rules" and leave only "extends" that are connected with react development. I'm not sure if we should include prettier in eslint. Prettier format is handled by 'npm run format' command.

**Comment by gbowne1** [comment]
What I *think* is happening is that we have conflicting configurations.

I would agree that this is over complicated.

The configuration that came with create react app is all we should need and it works with react...

@pawel975 @manuel12 I can close this PR. If someone wants to fix it, go ahead.

**Comment by pawel975** [comment]
> What I *think* is happening is that we have conflicting configurations.
> 
> I would agree that this is over complicated.
> 
> The configuration that came with create react app is all we should need and it works with react...
> 
> @pawel975 @manuel12 I can close this PR. If someone wants to fix it, go ahead.

I can do it @gbowne1

**Comment by gbowne1** [comment]
I am closing this because of changes to the structure, the new backend and ESLint decisions we are making.

**Pull request closed without merging**
